### ISSUE TITLE
jenkinsのインストールスクリプトが完了しない

### ISSUE THREAD

**Issue by myoo** [alminium/alminium#120]
さくらVPSでインストールを試みたところ、
sslサポート　yes
jenkinsインストール　yes
とするとインストールが完了しません。

```
--2014-02-23 22:06:35--  http://localhost:8080/jenkins/jnlpJars/jenkins-cli.jar
localhost をDNSに問いあわせています... ::1, 127.0.0.1
localhost|::1|:8080 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 503 Service Unavailable
2014-02-23 22:06:35 エラー 503: Service Unavailable。
```

でループから抜け出せなくなってしまいます。

jenkinsのインストールをoffにして試みるとすんなりインストールできます。

一旦jenkinsなしでインストール後、再度
sudo bash ./smelt
を試みたのですが、やはり同じ所で停止してしまいます。

http://HOSTNAME/jenkins に接続すると、以下のエラーメッセージが表示されます。

```
[!] エラー

hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.io.IOException: Unable to read /var/lib/jenkins/config.xml
    at hudson.WebAppMain$3.run(WebAppMain.java:234)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.io.IOException: Unable to read /var/lib/jenkins/config.xml
    at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:269)
    at jenkins.InitReactorRunner.run(InitReactorRunner.java:44)
    at jenkins.model.Jenkins.executeReactor(Jenkins.java:910)
    at jenkins.model.Jenkins.<init>(Jenkins.java:809)
    at hudson.model.Hudson.<init>(Hudson.java:82)
    at hudson.model.Hudson.<init>(Hudson.java:78)
    at hudson.WebAppMain$3.run(WebAppMain.java:222)
Caused by: java.io.IOException: Unable to read /var/lib/jenkins/config.xml
    at hudson.XmlFile.unmarshal(XmlFile.java:165)
    at jenkins.model.Jenkins$17.run(Jenkins.java:2562)
    at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
    at jenkins.model.Jenkins$7.runTask(Jenkins.java:899)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: com.thoughtworks.xstream.converters.ConversionException: org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm : org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm
---- Debugging information ----
message             : org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm
class               : hudson.model.Hudson
required-type       : hudson.model.Hudson
converter-type      : hudson.util.RobustReflectionConverter
path                : /hudson/securityRealm
line number         : 9
version             : not available
-------------------------------
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1061)
    at hudson.util.XStream2.unmarshal(XStream2.java:113)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1045)
    at hudson.XmlFile.unmarshal(XmlFile.java:163)
    ... 9 more
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm
    at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:56)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at hudson.util.XStream2$CompatibilityMapper.realClass(XStream2.java:279)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at hudson.util.xstream.MapperDelegate.realClass(MapperDelegate.java:43)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
    at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:49)
    at hudson.util.RobustReflectionConverter.determineType(RobustReflectionConverter.java:417)
    at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:285)
    at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:228)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    ... 18 more

ページ更新時: 2014/02/23 22:36:43Jenkins ver. 1.551
```

**Comment by IMAI-Yuji** [comment]
VirtualBox上のCentOS 6.5で同じ現象が置きました。

状況を確認するため、/var/lib/jenkins/config.xmlをcpしないようにjenkins-installスクリプトを改変をして試しました。これで、インストールは最後まで流れ、redmine, jenkinsともアクセスできるようになります。

```
diff --git a/inst-script/rhel6/jenkins-install b/inst-script/rhel6/jenkins-install
index f44becb..860559e 100644
--- a/inst-script/rhel6/jenkins-install
+++ b/inst-script/rhel6/jenkins-install
@@ -26,10 +26,10 @@ fi

 sed -i 's/JENKINS_ARGS=""/JENKINS_ARGS="--prefix=\/jenkins"/' /etc/sysconfig/jenkins

-if [ ! -f /var/lib/jenkins/config.xml ]
-then
-  cp config/jenkins-config.xml /var/lib/jenkins/config.xml
-fi
+# if [ ! -f /var/lib/jenkins/config.xml ]
+# then
+#   cp config/jenkins-config.xml /var/lib/jenkins/config.xml
+# fi

 if [ ! -f /var/lib/jenkins/plugins ]
 then
```

根本解決ではないですが、状況シェア情報としてお知らせします。

**Comment by akiko-pusu** [comment]
#116 でもJenkinsの設定の問題で失敗してしまう状況になっていました。dev側に思い当たる対応を追加していただいています。(commit: 00a867690ce6cd48e22ba374ebad3e9b7b8b0ad3)
masterブランチを使ってのセットアップでしょうか？
わたしも自分の環境で試してみようと思いますので、ご指示いただければ幸いです。

**Comment by myoo** [comment]
master$B%V%i%s%A$G%;%C%H%"%C%W$r9T$$$^$7$?!#(B
dev$B$G$O;n$7$F$$$^$;$s!#(B

2014$BG/(B2$B7n(B25$BF|2PMKF|!"(BAkiko Takanonotifications@github.com$B$5$s$O=q$-$^$7$?(B:

**Comment by akiko-pusu** [comment]
Jenkinsの件、再現いたしました。Alminiumのconfig.xmlを適用してjenkinsを起動させると、503エラーが発生し、後続のプラグイン追加も失敗するようです。

**Comment by myoo** [comment]
申し訳ありません、iPhoneからの返信で文字化けしてしまいました。

masterブランチを使ってセットアップを行いました。
devでは行っていません。

**Comment by mikoto20000** [comment]
masterブランチに最新の全てのコードをマージしました。これで、修正されていると思いますが、
もしよろしければ、masterブランチでセットアップをやり直してみていただけますか？

よろしくお願いします。

**Comment by IMAI-Yuji** [comment]
git pullでmasterでセットアップをしてみました。しかし、残念ながら503エラーになります。/var/log/jenkins/jenkins.logに Unable to read /var/lib/jenkins/config.xml と出ています。

オペミスかもしれないので、念のためCentOS 6.5をクリーンインストールして試してみます。

**Comment by myoo** [comment]
こちらでも確認しましたが、やはり503エラーで止まってしまいます。

```
Feb 23, 2014 7:32:03 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading global config
java.io.IOException: Unable to read /var/lib/jenkins/config.xml
        at hudson.XmlFile.unmarshal(XmlFile.java:165)
        at jenkins.model.Jenkins$17.run(Jenkins.java:2562)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
```

**Comment by IMAI-Yuji** [comment]
試してみましたが、同じ現象でエラーになります。

**Comment by mikoto20000** [comment]
myooさん、IMAI-Yujiさん、ご確認ありがとうございます。

現象を確認したところ、Jenkinsが起動できていないので、Jenkinsに接続しjenkins-cli.jarを取得するところで503エラーが表示されているようでした。

Jenkinsが起動できない原因として、config.xmlの

```
  <securityRealm class="org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm" plugin="reverse-proxy-auth-plugin">
```

を読み込むところでエラーになっています。この設定の実行にreverse-proxy-auth-pluginが必要そうです。ですが、インストーラ上設定ファイルをコピーした後で、reverse-proxy-auth-pluginを必要としているので、エラーとなっているような気がします。

inst-script/rhel6/jenkins-install 

```
   ...(省略)...
   #   cp config/jenkins-config.xml /var/lib/jenkins/config.xml
  ...(省略)...
  java -jar $INSTALL_DIR/bin/jenkins-cli.jar -s http://localhost:8080/jenkins/ install-plugin reverse-proxy-auth-plugin
```

そこで、config.xmlを

```
  <!--
  <securityRealm class="org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm" plugin="reverse-proxy-auth-plugin">
    <authContext/>
    <inhibitInferRootDN>false</inhibitInferRootDN>
    <userSearchBase></userSearchBase>
    <userSearch>uid={0}</userSearch>
    <forwardedUser>X-Forwarded-User</forwardedUser>
    <authorities/>
  </securityRealm>
  -->
```

と一旦コメントアウトし、手動でproxy-auth-pluginをJenkinsからインストール。上記コメントを戻し再起動すると、下記のエラーがjenkins.logに出力され、jenkinsが正常に起動しない状態となっています。

```
  WARNING: 
  java.lang.NullPointerException
        at org.eclipse.jetty.util.StringUtil.getBytes(StringUtil.java:378)
        at org.eclipse.jetty.io.ByteArrayBuffer.<init>(ByteArrayBuffer.java:81)
        at org.eclipse.jetty.io.ByteArrayBuffer$CaseInsensitive.<init>(ByteArrayBuffer.java:424)
        at org.eclipse.jetty.io.BufferCache$CachedBuffer.<init>(BufferCache.java:134)
        at org.eclipse.jetty.io.BufferCache.lookup(BufferCache.java:101)
        at org.eclipse.jetty.http.HttpFields.getField(HttpFields.java:402)
        at org.eclipse.jetty.http.HttpFields.getStringField(HttpFields.java:431)
        at org.eclipse.jetty.server.Request.getHeader(Request.java:605)
        at org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm$1.doFilter(ReverseProxySecurityRealm.java:395)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
```

reverse-proxy-auth-pluginに何らかの不具合がありそうな気がしますが、詳細は解析できていません。いまのところIMAI-Yuji のコメントにあるように、設定ファイルをコピーする部分をコメントアウトするしかなさそうです。

長々と書いてしまったのでポイントをまとめますと、
1. reverse-proxy-auth-pluginをインストールする前にconfig.xmlにsecurityRealmの設定を行っているのが悪い？
2. reverse-proxy-auth-pluginに何らかの問題(あるいは使い方が変更になった)可能性があるため問題が発生した？

この2点が怪しいかも。時間があるときにもう少しみてみますが、まずは、情報の共有まで。

**Comment by akiko-pusu** [comment]
Reverse Proxy Authをいったん無効にして、認証無しでJenkinsを起動し、そのあとでReverse Proxy Authを有効にして、設定を確認してみました。
この時点（Exceptionが出ないケース）でのsecurityRealmの設定は、下記の通りになっていました。

```
 <securityRealm class="org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm" plugin="reverse-proxy-auth-plugin">
    <proxyTemplate/>
    <authContext/>
    <inhibitInferRootDN>false</inhibitInferRootDN>
    <userSearchBase></userSearchBase>
    <userSearch>uid={0}</userSearch>
    <authorities/>
    <forwardedUser>X-Forwarded-User</forwardedUser>
    <headerGroups>X-Forwarded-Groups</headerGroups>
    <headerGroupsDelimiter>|</headerGroupsDelimiter>
  </securityRealm>
```

Jenkins本体の変更も影響しているのかもしれませんね。

jenkinsのインストールスクリプト側も、
1. rpmでjenkinsインストール
2. 設定を変えない状態で、install-pluginを実施
3. 必要なjenkinsのプラグインが入ったあとで、jenkins-config.xml を差し替え
   　（上記のsecurityRealmの内容に修正したもの）
4. jenkins restart

という対応をすると、一応エラーが無く起動となっています。
良かったら差分をアップします。

**Comment by mikoto20000** [comment]
akiko_pusuさん、ご確認ありがとうございます！
仕事が早いですね^^

devブランチへプルリクエスト頂けるとありがたいです。
よろしくお願いします。

**Comment by myoo** [comment]
お世話になります。

上記アップしていただいたconfig.xmlの内容に差し替えて起動すると、
エラーなく起動はするのですがjenkinsの管理画面で

```
リバースプロキシーの設定がおかしいようです
```

のアラートが表示されてしまいます。

**Comment by mikoto20000** [comment]
config.xmlをコメントアウトした状態でしょうか。もし、Jenkinsのプラグインフォルダにreverse-proxy-auth-pluginがあるなら、

```
# rm -fr /var/lib/jenkins/plugins/reverse-proxy-auth-plugin*
# service jenkins restart
```

でプラグインを削除して、jenkinsを再起動するとどうなるでしょうか？

よろしくお願いします。

**Comment by myoo** [comment]
config.xmlをコメントアウトした状態でインストールスクリプトを実行し、

```
cp config/jenkins-config.xml /var/lib/jenkins/config.xml
```

を実行してから、securityRealm の部分を

```
<securityRealm class="org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm" plugin="reverse-proxy-auth-plugin">
    <proxyTemplate/>
    <authContext/>
    <inhibitInferRootDN>false</inhibitInferRootDN>
    <userSearchBase></userSearchBase>
    <userSearch>uid={0}</userSearch>
    <authorities/>
    <forwardedUser>X-Forwarded-User</forwardedUser>
    <headerGroups>X-Forwarded-Groups</headerGroups>
    <headerGroupsDelimiter>|</headerGroupsDelimiter>
  </securityRealm>
```

で置き換え、jenkinsをリスタートしました。

**Comment by mikoto20000** [comment]
mypoさん

proxyのワーニングがでることを確認しましたが、Apacheの設定がおかしいと表示されるみたいですが、設定を見直してもちょっと原因が分かりませんでした。取り敢えず問題なさそうであればそのまま使ってみてください。

**Comment by mikoto20000** [comment]
akik_pusuさんに修正頂いたコードをdevブランチにマージしました。

```
# git checkout dev
# git pull
```

で更新するとご利用いただけます。

**Comment by IMAI-Yuji** [comment]
mikoto2000さん、devブランチで動作することが確認できました。ありがとうございます。
残件は、「リバースプロキシーの設定がおかしいようです。」への対応ですね。

**Comment by mikoto20000** [comment]
みなさん、ご協力ありがとうございました。このIssueは一旦閉じます。

リバースプロキシの設定のアラートについては、#122 で引き続き議論していきます。

**Comment by myoo** [comment]
ありがとうございました
