### ISSUE TITLE
centos6.6にalminiumをインストール後、初期画面が開かない

### ISSUE THREAD

**Issue by kossie** [alminium/alminium#173]
alminiumをインストール後、初期画面を開こうとするとRedmineのエラー画面に遷移します。
httpdのエラーログを見たところ以下のログが記載されておりました。
インストール自体はできていると思うのですが、passengerのLoadでエラーが発生しているように思えます。

再現方法

---

VirtualBoxで動かしているCentOS6.6minimal(ホストOSはWin8.1)に下記の通りインストール

git clone後にsudo ./smeltを実行
SSL :N
メール : N
jenkins : N
SELinux/Firewall : Y

alminiumインストール後に以下のissueを実行してます
[alminiumインストール passenger5.0.4でのapache起動失敗 #169](https://github.com/alminium/alminium/issues/169)

---

```
Could not spawn process for application /opt/alminium: An error occured while starting up the preloader.
  Error ID: 0bd924cd
  Error details saved to: /tmp/passenger-error-Dk7yEj.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
  <li>Is this app supposed to be run as the <code>apache</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
</ol>

<p>-------- The exception is as follows: -------</p>
Could not find gem &#39;simplecov-rcov (&gt;= 0) ruby&#39; in the gems available on this machine. (Bundler::GemNotFound)
<pre>  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:333:in `block in verify_gemfile_dependencies_are_found!&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:307:in `each&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:307:in `verify_gemfile_dependencies_are_found!&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:199:in `start&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:182:in `resolve&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:193:in `resolve&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/setup.rb:18:in `&lt;top (required)&gt;&#39;
  /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require&#39;
  /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require&#39;
  /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:278:in `block in run_load_path_setup_code&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:381:in `running_bundler&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:276:in `run_load_path_setup_code&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:99:in `preload_app&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:157:in `&lt;module:App&gt;&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:29:in `&lt;module:PhusionPassenger&gt;&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:28:in `&lt;main&gt;&#39;</pre>

```

**Comment by cyder222** [comment]
私も同じような現象にあっています。
CentOS 6 64bit(VPS)を用いています。
SSL :N
メール : N
 jenkins : Y
 SELinux/Firewall : Y

インストール後
alminiumインストール passenger5.0.4でのapache起動失敗 #169

を実行した後、ブラウザから起動すると

```
[ 2015-04-08 16:39:01.5392 8889/7f4cfb68a700 App/Implementation.cpp:287 ]: Could not spawn process for application /opt/alminium: An error occured while starting up the preloader
.
  Error ID: a4ee15a5
  Error details saved to: /tmp/passenger-error-H9oZ5c.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
  <li>Is this app supposed to be run as the <code>apache</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
</ol>

<p>-------- The exception is as follows: -------</p>
Could not find gem &#39;holidays (~&gt; 1.0.3) ruby&#39; in the gems available on this machine. (Bundler::GemNotFound)
<pre>  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:333:in `block in verify_gemfile_dependencies_are_found!&#39;
 /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:307:in `each&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:307:in `verify_gemfile_dependencies_are_found!&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:199:in `start&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:182:in `resolve&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:193:in `resolve&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/setup.rb:18:in `&lt;top (required)&gt;&#39;
  /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require&#39;
  /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require&#39;
  /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:278:in `block in run_load_path_setup_code&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:381:in `running_bundler&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:276:in `run_load_path_setup_code&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:99:in `preload_app&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:157:in `&lt;module:App&gt;&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:29:in `&lt;module:PhusionPassenger&gt;&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:28:in `&lt;main&gt;&#39;</pre>

[ 2015-04-08 16:39:01.6288 8889/7f4cf5efb700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is a4ee15a5. Please see earlier logs for details about the error.
App 8927 stdout:
App 8927 stdout:
[ 2015-04-08 16:42:03.3375 8889/7f4cfb68a700 App/Implementation.cpp:287 ]: Could not spawn process for application /opt/alminium: An error occured while starting up the preloader.
  Error ID: acb07c2d
  Error details saved to: /tmp/passenger-error-FinayW.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
 <li>Is this app supposed to be run as the <code>apache</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
</ol>

<p>-------- The exception is as follows: -------</p>
Could not find gem &#39;holidays (~&gt; 1.0.3) ruby&#39; in the gems available on this machine. (Bundler::GemNotFound)
<pre>  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:333:in `block in verify_gemfile_dependencies_are_found!&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:307:in `each&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:307:in `verify_gemfile_dependencies_are_found!&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:199:in `start&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:182:in `resolve&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:193:in `resolve&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/setup.rb:18:in `&lt;top (required)&gt;&#39;
  /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require&#39;
  /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require&#39;
  /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:278:in `block in run_load_path_setup_code&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:381:in `running_bundler&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/loader_shared_helpers.rb:276:in `run_load_path_setup_code&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:99:in `preload_app&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:157:in `&lt;module:App&gt;&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:29:in `&lt;module:PhusionPassenger&gt;&#39;
  /usr/lib64/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:28:in `&lt;main&gt;&#39;</pre>

[ 2015-04-08 16:42:03.4305 8889/7f4cf54fa700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is acb07c2d. Please see earlier logs for details about the error.
```

といったエラーログを残します。
