### ISSUE TITLE
git_branch_hook

### ISSUE THREAD

**Issue by mikoto20000** [alminium/alminium#31]
1.4.xで動作確認

https://github.com/mikoto20000/redmine_git_branch_hook.git

**Comment by mikoto20000** [comment]
GitAdapterから，scm_cmdメソッドがなくなっている。

```
NoMethodError (undefined method `scm_cmd' for #<Redmine::Scm::Adapters::GitAdapter:0x00000005bcabd8>):
  app/models/repository/git.rb:164:in `save_revisions'
  app/models/repository/git.rb:154:in `fetch_changesets'
  app/controllers/repositories_controller.rb:91:in `show'
  <internal:prelude>:10:in `synchronize'
  passenger (3.0.12) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.12) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  passenger (3.0.12) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `block in handle_spawn_application'
```

**Comment by mikoto20000** [comment]
アップストーリが対応されたのでプラグインを有効化しました。
