### ISSUE TITLE
インストール後エラーページが表示されて、ALMiniumの閲覧が一切できない

### ISSUE THREAD

**Issue by yuma300** [alminium/alminium#86]
You cannot specify the same gem twice with different version requirements. You specified: capybara (~> 2.0.0) and capybara (>= 0) (Bundler::GemfileError)

上記エラーメッセージが表示されるだけで正常に表示できません。

**Comment by hiroshi-maruyama** [comment]
私も同様のエラーが発生しました．
　環境はUbuntu 12.04 Server 64bitです．

　何も追加せずにOSをインストールし，update & upgrade後に以下の手順でインストールしました．

``` bash
$ sudo aptitude install git
$ git clone https://github.com/alminium/alminium.git
$ sudo su
# cd alminium
# bash ./smelt
```

　途中で３度ほどMySQLのrootパスワードを聞かれましたが，すべて空欄でENTERしたところ，最後の方で以下のエラーメッセージが表示されました．

``` bash
Cloning into 'cache/redmine_git_branch_hook'...
remote: Counting objects: 64, done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 64 (delta 24), reused 46 (delta 6)
Unpacking objects: 100% (64/64), done.
Already on 'master'
/home/example/alminium /home/example/alminium
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
(eval):7: warning: already initialized constant RAILS_VERSION_IS_3
You cannot specify the same gem twice with different version requirements.
You specified: capybara (>= 0) and capybara (~> 2.0.0)
(eval):7: warning: already initialized constant RAILS_VERSION_IS_3
You cannot specify the same gem twice with different version requirements.
You specified: capybara (>= 0) and capybara (~> 2.0.0)

(eval):7: warning: already initialized constant RAILS_VERSION_IS_3
You cannot specify the same gem twice with different version requirements.
You specified: capybara (>= 0) and capybara (~> 2.0.0)

(eval):7: warning: already initialized constant RAILS_VERSION_IS_3
You cannot specify the same gem twice with different version requirements.
You specified: capybara (>= 0) and capybara (~> 2.0.0)

(eval):7: warning: already initialized constant RAILS_VERSION_IS_3
You cannot specify the same gem twice with different version requirements.
You specified: capybara (>= 0) and capybara (~> 2.0.0)

(eval):7: warning: already initialized constant RAILS_VERSION_IS_3
You cannot specify the same gem twice with different version requirements.
You specified: capybara (>= 0) and capybara (~> 2.0.0)

(eval):7: warning: already initialized constant RAILS_VERSION_IS_3
You cannot specify the same gem twice with different version requirements.
You specified: capybara (>= 0) and capybara (~> 2.0.0)

/home/example/alminium
inst-script/gen-email-config.sh: 行 46: 予期しないトークン `fi' 周辺に構文エラーがあります
inst-script/gen-email-config.sh: 行 46: `        fi'
Enabling module expires.
To activate the new configuration, you need to run:
  service apache2 restart
Considering dependency dav for dav_fs:
Module dav already enabled
Enabling module dav_fs.
To activate the new configuration, you need to run:
  service apache2 restart
Enabling module auth_mysql.
To activate the new configuration, you need to run:
  service apache2 restart
Considering dependency dav_svn for authz_svn:
Considering dependency dav for dav_svn:
Module dav already enabled
Module dav_svn already enabled
Enabling module authz_svn.
To activate the new configuration, you need to run:
  service apache2 restart
Enabling site redmine.
To activate the new configuration, you need to run:
  service apache2 reload
Enabling site vcs.
To activate the new configuration, you need to run:
  service apache2 reload
 * Stopping web server apache2
apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
 ... waiting                                                                                                                                                                                                                          [ OK ]
 * Starting web server apache2
apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
```

　ブラウザでアクセスすると，passengerのエラーページが表示され，

   You cannot specify the same gem twice with different version requirements. You specified: capybara (>= 0) and capybara (~> 2.0.0) (Bundler::GemfileError)

　と表示されています．

**Comment by mikoto20000** [comment]
Redmine HudsonプラグインのgemのバージョンがRedmine2.2.xもしくは他のプラグインとコンフリクトを起こしていたため、エラーがでるようになったようです。正しく動作するHudsonプラグインのバージョンを指定するようにmasterブランチを修正しました。

@yuma300 さん
uninstall スクリプトを実行し、一度綺麗にしてから再度インストールしてみてください。

@hiroshi-maruyama 
Ubuntuは試していませんが、多分動くのではないかと思います(確証が持てずスミマセン)。
Ubuntuは最近あまりテストしていないので、別の問題で動作しないかもしれません。

**Comment by hiroshi-maruyama** [comment]
無事導入できました．素早い対応ありがとうございます．

```
inst-script/gen-email-config.sh: 行 46: 予期しないトークン `fi' 周辺に構文エラーがあります
inst-script/gen-email-config.sh: 行 46: `        fi'
```

というエラーは以前と変わらず出力されますが，メールの設定はしていないので，今のところ問題ありません．

**Comment by drakontia** [comment]
@hiroshi-maruyama さん
すいません。その部分はUbuntuでの日本語フォントのパッケージ名とインストールフォルダが分からずにコメントアウトして回避していましたが、きちんと書けていませんでした。
もし上記についてご存じでしたら教えて頂けないでしょうか。こちらで修正しますので、よろしくお願いします。

**Comment by m-enomoto** [comment]
CentOS6.4にて、2013/5/10にインストールを実施したのですが、やはりpassengerのエラーページが表示されてしまいます。実施したコマンドは下記の通りです。

$ git clone https://github.com/alminium/alminium.git
~以下略~
Resolving deltas: 100% (1823/1823), done.

$ git tag
v0.1rhel
v0.9.0
v1.0.0
v1.1.0
v1.1.1
v1.1.2
v1.1.3
v1.1.4
v1.1.5
v1.1.6
v1.2.0
v1.2.1
v1.2.2
v1.2.3
v1.2.4
v2.0.0
v2.0.0beta1
v2.0.0rc1
v2.0.3
v2.2.0
v2.2.1
v2.2.2
v2.2.2-2
v2.2.4

$git checkout v2.2.4

$./smelt

●smelt中に下記のようなメッセージが出ていたのが気になります・・
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.

●https://github.com/alminium/alminium/issues/87 の設定を実施。

**Comment by mikoto20000** [comment]
ご連絡ありがとうございます。

checkout v2.2.4を行わず、masterブランチのheadで実行してみて頂けますか?

よろしくお願いいたします。

**Comment by m-enomoto** [comment]
早速のご回答ありがとうございます！

git tag/git checkoutは実施せず、そのまま/smeltで問題なくインストールできました。
www.atmarkit.co.jp/fjava/rensai4/scrum03/02.html
の通りでは駄目なのですね・・

**Comment by mikoto20000** [comment]
すいません。まだタグを打っていませんでした。

v2.2.4-2としてタグを打ったので、最新のタグを利用すればインストールできると思います。

**Comment by hiroshi-maruyama** [comment]
遅くなりましたが，Ubuntu12.04での日本語フォントのパッケージ名とインストールフォルダについてです．

```
/usr/share/fonts/truetype/
```

上記が標準のインストールフォルダになっています．
が，初期状態では日本語フォントが入っていません．

```
$ sudo apt-get install fonts-ipafont-gothic
```

とインストールすると，

```
/usr/share/fonts/truetype/fonts-japanese-gothic.ttf
/usr/share/fonts/truetype/fonts-japanese-mincho.ttf
```

ができあがります．ただ，シンボリックリンクのようで，実体は，

```
/etc/alternatives/fonts-japanese-gothic.ttf
/etc/alternatives/fonts-japanese-mincho.ttf
```

にありました．

**Comment by drakontia** [comment]
@hiroshi-maruyama さん、ありがとうございます。
修正したものをdevブランチに適用しましたので、ご確認頂ければと思います。
よろしくお願いします。

**Comment by hiroshi-maruyama** [comment]
クリーンな環境で，
    $ sudo apt-get install fonts-ipafont-gothic
    $ git clone https://github.com/alminium/alminium.git
    $ cd alminium
    $ git checkout origin/dev
    $ sudo su
    # bash ./smelt
　した結果，Terminal上はエラーがでなかったのですが，ブラウザでアクセスしてみると，passengerが「Web application could not be started」のエラー画面を出力しました．

```
  (/opt/alminium/config/configuration.yml): couldn't parse YAML at line 19 column 11 (Psych::SyntaxError)
  /usr/lib/ruby/1.9.1/psych.rb:154:in `parse'
  /usr/lib/ruby/1.9.1/psych.rb:154:in `parse_stream'
  /usr/lib/ruby/1.9.1/psych.rb:125:in `parse'
  /usr/lib/ruby/1.9.1/psych.rb:112:in `load'
  /usr/lib/ruby/1.9.1/psych.rb:229:in `load_file'
  /opt/alminium/lib/redmine/configuration.rb:85:in `load_from_yaml'
  /opt/alminium/lib/redmine/configuration.rb:42:in `load'
  /opt/alminium/lib/redmine/configuration.rb:66:in `[]'
  /opt/alminium/lib/redmine/thumbnail.rb:24:in `<module:Thumbnail>'
  /opt/alminium/lib/redmine/thumbnail.rb:21:in `<module:Redmine>'
  /opt/alminium/lib/redmine/thumbnail.rb:20:in `<top (required)>'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
  /opt/alminium/lib/redmine.rb:42:in `<top (required)>'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
  /opt/alminium/config/initializers/30-redmine.rb:4:in `<top (required)>'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `block in load'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb:587:in `each'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb:587:in `block in <class:Engine>'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /opt/alminium/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /opt/alminium/vendor/bundler/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.2/helper-scripts/rack-preloader.rb:82:in `eval'
  /var/lib/gems/1.9.1/gems/passenger-4.0.2/helper-scripts/rack-preloader.rb:82:in `preload_app'
  /var/lib/gems/1.9.1/gems/passenger-4.0.2/helper-scripts/rack-preloader.rb:127:in `<module:App>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.2/helper-scripts/rack-preloader.rb:6:in `<module:PhusionPassenger>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.2/helper-scripts/rack-preloader.rb:5:in `<main>'
```

　以降，Rubyのバージョン情報（/usr/bin/ruby1.9.3）や，ロードしたライブラリのリスト，メモリ使用状況などの出力が続きました．

**Comment by mikoto20000** [comment]
メールの設定スクリプトにメールの設定以外の情報が入っていたり、バグがあったりしたので、リファクタリングしました。
mail-refactoringブランチにて修正しています。

このIssueは閉じられており、もともとの議論とは関係なくなっているので#88で続きは議論します。
